<?php
/**
 * This function records fields for the acf.
 */
function register_custom_acf_fields_template_country_narrative() {
    if ( function_exists( 'acf_add_local_field_group' ) ) {
        acf_add_local_field_group( [
                'key'                   => 'group_template_country_narrative',
                'title'                 => 'Country Narrative',
                'fields'                => [
                    [
                        'key'          => 'field_subtitle_text',
                        'label'        => 'Subtitle',
                        'name'         => 'subtitle_text',
                        'type'         => 'text',
                        'instructions' => '',
                        'required'     => 1,
                    ],
                    //Driver Component.
                    [
                        'key'               => 'field_tab_drivers',
                        'label'             => 'Drivers Tab',
                        'name'              => 'tab_drivers',
                        'type'              => 'tab',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                    ],
                    [
                        'key'               => 'field_driver_image',
                        'label'             => 'Image',
                        'name'              => 'driver_image',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'return_format'     => 'url',
                        'preview_size'      => 'medium',
                        'library'           => 'all',
                    ],
                    [
                        'key'               => 'field_driver_description',
                        'label'             => 'Description',
                        'name'              => 'driver_description',
                        'type'              => 'wysiwyg',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'default_value'     => '',
                        'tabs'              => 'all',
                        'toolbar'           => 'full',
                        'media_upload'      => 1,
                        'delay'             => 0,
                    ],
                    [
                        'key'          => 'field_driver_button_text',
                        'label'        => 'Button Text',
                        'name'         => 'driver_button_text',
                        'type'         => 'text',
                        'instructions' => '',
                        'required'     => 1,
                        'wrapper'      => [
                            'width' => '50',
                        ],
                    ],
                    [
                        'key'               => 'field_driver_link_button',
                        'label'             => 'Button Link',
                        'name'              => 'driver_link_button',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '50',
                        ],
                    ],
                    // Actors and activities component.
                    [
                        'key'               => 'field_tab_actors_activities',
                        'label'             => 'Actors-Activities Tab',
                        'name'              => 'tab_actors_activities',
                        'type'              => 'tab',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                    ],
                    [
                        'key'               => 'field_actors_activities_image',
                        'label'             => 'Image',
                        'name'              => 'actors_activities_image',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'return_format'     => 'url',
                        'preview_size'      => 'medium',
                        'library'           => 'all',
                    ],
                    [
                        'key'               => 'field_actors_activities_description',
                        'label'             => 'Description',
                        'name'              => 'actors_activities_description',
                        'type'              => 'wysiwyg',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'default_value'     => '',
                        'tabs'              => 'all',
                        'toolbar'           => 'full',
                        'media_upload'      => 1,
                        'delay'             => 0,
                    ],
                    [
                        'key'          => 'field_actors_activities_button_text',
                        'label'        => 'Button Text',
                        'name'         => 'actors_activities_button_text',
                        'type'         => 'text',
                        'instructions' => '',
                        'required'     => 1,
                        'wrapper'      => [
                            'width' => '50',
                        ],
                    ],
                    [
                        'key'               => 'field_actors_activities_link_button',
                        'label'             => 'Button Link',
                        'name'              => 'actors_activities_link_button',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '50',
                        ],
                    ],
                    // Food environment component.
                    [
                        'key'               => 'field_tab_food_environment',
                        'label'             => 'Food-Environment Tab',
                        'name'              => 'tab_food_environment',
                        'type'              => 'tab',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                    ],
                    [
                        'key'               => 'field_food_environment_image',
                        'label'             => 'Image',
                        'name'              => 'food_environment_image',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'return_format'     => 'url',
                        'preview_size'      => 'medium',
                        'library'           => 'all',
                    ],
                    [
                        'key'               => 'field_food_environment_description',
                        'label'             => 'Description',
                        'name'              => 'food_environment_description',
                        'type'              => 'wysiwyg',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'default_value'     => '',
                        'tabs'              => 'all',
                        'toolbar'           => 'full',
                        'media_upload'      => 1,
                        'delay'             => 0,
                    ],
                    [
                        'key'          => 'field_food_environment_button_text',
                        'label'        => 'Button Text',
                        'name'         => 'food_environment_button_text',
                        'type'         => 'text',
                        'instructions' => '',
                        'required'     => 1,
                        'wrapper'      => [
                            'width' => '50',
                        ],
                    ],
                    [
                        'key'               => 'field_food_environment_link_button',
                        'label'             => 'Button Link',
                        'name'              => 'food_environment_link_button',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '50',
                        ],
                    ],
                    // Consumer behavior component.
                    [
                        'key'               => 'field_tab_consumer_behavior',
                        'label'             => 'Consumer-Behavior Tab',
                        'name'              => 'tab_consumer_behavior',
                        'type'              => 'tab',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                    ],
                    [
                        'key'               => 'field_consumer_behavior_image',
                        'label'             => 'Image',
                        'name'              => 'consumer_behavior_image',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'return_format'     => 'url',
                        'preview_size'      => 'medium',
                        'library'           => 'all',
                    ],
                    [
                        'key'               => 'field_consumer_behavior_description',
                        'label'             => 'Description',
                        'name'              => 'consumer_behavior_description',
                        'type'              => 'wysiwyg',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'default_value'     => '',
                        'tabs'              => 'all',
                        'toolbar'           => 'full',
                        'media_upload'      => 1,
                        'delay'             => 0,
                    ],
                    [
                        'key'          => 'field_consumer_behavior_button_text',
                        'label'        => 'Button Text',
                        'name'         => 'consumer_behavior_button_text',
                        'type'         => 'text',
                        'instructions' => '',
                        'required'     => 1,
                        'wrapper'      => [
                            'width' => '50',
                        ],
                    ],
                    [
                        'key'               => 'field_consumer_behavior_link_button',
                        'label'             => 'Button Link',
                        'name'              => 'consumer_behavior_link_button',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '50',
                        ],
                    ],
                    // Outcomes component.
                    [
                        'key'               => 'field_tab_outcomes',
                        'label'             => 'Outcomes Tab',
                        'name'              => 'tab_outcomes',
                        'type'              => 'tab',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                    ],
                    [
                        'key'               => 'field_outcomes_image',
                        'label'             => 'Image',
                        'name'              => 'outcomes_image',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'return_format'     => 'url',
                        'preview_size'      => 'medium',
                        'library'           => 'all',
                    ],
                    [
                        'key'               => 'field_outcomes_description',
                        'label'             => 'Description',
                        'name'              => 'outcomes_description',
                        'type'              => 'wysiwyg',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'default_value'     => '',
                        'tabs'              => 'all',
                        'toolbar'           => 'full',
                        'media_upload'      => 1,
                        'delay'             => 0,
                    ],
                    [
                        'key'          => 'field_outcomes_button_text',
                        'label'        => 'Button Text',
                        'name'         => 'outcomes_button_text',
                        'type'         => 'text',
                        'instructions' => '',
                        'required'     => 1,
                        'wrapper'      => [
                            'width' => '50',
                        ],
                    ],
                    [
                        'key'               => 'field_outcomes_link_button',
                        'label'             => 'Button Link',
                        'name'              => 'outcomes_link_button',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '50',
                        ],
                    ],
                ],
                'location'              => [
                    [
                        [
                            'param'    => 'post_type',
                            'operator' => '==',
                            'value'    => 'country-narrative',
                        ],
                    ],
                ],
                'menu_order'            => 0,
                'position'              => 'acf_after_title',
                'style'                 => 'default',
                'label_placement'       => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen'        => '',
                'active'                => true,
                'show_in_rest'          => 1,
            ]
        );
    }
}

add_action( 'init', 'register_custom_acf_fields_template_country_narrative' );
