<?php
/**
 * This function records fields for the acf.
 */
function register_custom_acf_fields_page_home() {

    if ( function_exists( 'acf_add_local_field_group' ) ):
        acf_add_local_field_group( array(
            'key'                   => 'group_63174b101581a',
            'title'                 => 'Page Home',
            'fields'                => array(
                array(
                    'key'               => 'field_63174b5b5d8af',
                    'label'             => 'Short Description',
                    'name'              => 'short_description',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_631767a1d0f8b',
                    'label'             => 'First Section',
                    'name'              => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_631767c6d0f8d',
                    'label'             => 'F Title',
                    'name'              => 'f_title',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_631767e4d0f8e',
                    'label'             => 'F Description',
                    'name'              => 'f_description',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '70',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'tabs'              => 'all',
                    'toolbar'           => 'full',
                    'media_upload'      => 1,
                    'delay'             => 0,
                ),
                array(
                    'key'               => 'field_631767f9d0f8f',
                    'label'             => 'F Image',
                    'name'              => 'f_image',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '30',
                        'class' => '',
                        'id'    => '',
                    ),
                    'return_format'     => 'url',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ),
                array(
                    'key'               => 'field_63176815d0f90',
                    'label'             => 'F Text Buttom',
                    'name'              => 'f_text_buttom',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_6317681fd0f91',
                    'label'             => 'F Link Buttom',
                    'name'              => 'f_link_buttom',
                    'type'              => 'page_link',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'post_type'         => array(
                        0 => 'page',
                    ),
                    'taxonomy'          => '',
                    'allow_null'        => 0,
                    'allow_archives'    => 1,
                    'multiple'          => 0,
                ),
                array(
                    'key'               => 'field_631769cbd553d',
                    'label'             => 'Second Section',
                    'name'              => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_631769f8d553f',
                    'label'             => 'S Title',
                    'name'              => 's_title',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '70',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_63176a10d5540',
                    'label'             => 'S Image',
                    'name'              => 's_image',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '30',
                        'class' => '',
                        'id'    => '',
                    ),
                    'return_format'     => 'url',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ),
                array(
                    'key'               => 'field_63176a5310c5f',
                    'label'             => 'S Text Buttom',
                    'name'              => 's_text_buttom',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_63176a5610c60',
                    'label'             => 'S Link Buttom',
                    'name'              => 's_link_buttom',
                    'type'              => 'page_link',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'post_type'         => array(
                        0 => 'page',
                    ),
                    'taxonomy'          => '',
                    'allow_null'        => 0,
                    'allow_archives'    => 1,
                    'multiple'          => 0,
                ),
                array(
                    'key'               => 'field_63176a8c3ef8c',
                    'label'             => 'Third Section',
                    'name'              => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_6317703d88d88',
                    'label'             => 'T Title',
                    'name'              => 't_title',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_6317704d88d89',
                    'label'             => 'T Description',
                    'name'              => 't_description',
                    'type'              => 'wysiwyg',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '70',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'tabs'              => 'all',
                    'toolbar'           => 'full',
                    'media_upload'      => 1,
                    'delay'             => 0,
                ),
                array(
                    'key'               => 'field_6317705d88d8a',
                    'label'             => 'T Image',
                    'name'              => 't_image',
                    'type'              => 'image',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '30',
                        'class' => '',
                        'id'    => '',
                    ),
                    'return_format'     => 'url',
                    'preview_size'      => 'medium',
                    'library'           => 'all',
                    'min_width'         => '',
                    'min_height'        => '',
                    'min_size'          => '',
                    'max_width'         => '',
                    'max_height'        => '',
                    'max_size'          => '',
                    'mime_types'        => '',
                ),
                array(
                    'key'               => 'field_6317706c88d8b',
                    'label'             => 'T Text Buttom',
                    'name'              => 't_text_buttom',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'prepend'           => '',
                    'append'            => '',
                    'maxlength'         => '',
                ),
                array(
                    'key'               => 'field_6317707088d8c',
                    'label'             => 'T Link Buttom',
                    'name'              => 't_link_buttom',
                    'type'              => 'page_link',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'post_type'         => array(
                        0 => 'page',
                    ),
                    'taxonomy'          => '',
                    'allow_null'        => 0,
                    'allow_archives'    => 1,
                    'multiple'          => 0,
                ),
            ),
            'location'              => array(
                array(
                    array(
                        'param'    => 'page_type',
                        'operator' => '==',
                        'value'    => 'front_page',
                    ),
                ),
            ),
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
            'show_in_rest'          => 0,
        ) );

    endif;
}

add_action( 'init', 'register_custom_acf_fields_page_home' );
